# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 也无风雨也无晴
subtitle: ''
description: '好记性不如烂键盘'
keywords:
author: chaxxro
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://chaxxro.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:month/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
# 名称默认是在文章里面设置的，如果是中文名称，那么路径名也会是中文，这里可以将中文映射成英文
category_map:
# # 一级分类
#   Android: android
#   Java: java
#   Hexo: hexo
#   Web前端: web
#   Linux: linux
#   Mac: mac
#   设计: design
# # 二级分类
#   学习笔记: learning
#   API: api
#   主题: theme
#   CSS: css
#   HTML5: html
#   JavaScript: js
#   常用命令: command
#   反编译: reverse
#   安全: security
#   优化: optimization
#   Material Design: material-design
#   字体: font
#   源码分析: source-code
    
tag_map:
  # 字体: font
  # Android Studio: android-studio
  # Android API: android-API
  # Android Widget: android-widget
  # Android 源码分析: android-source
  # JDK: JDK
  # Hexo建站: hexo-blog
  # Hexo 配置: hexo-config
  # Hexo 主题: hexo-themes
  # EJS教程: ejs
  # HTML5: html
  # CSS3: css 
  # JS: js
  # git: git
  # 常用工具: tools
  # NexT: theme-next
  # git子项目: git-submodule

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/chaxxro/chaxxro.github.io.git
  branch: gh-pages
  message: {{ now('YYYY-MM-DD HH:mm:ss') }}